name: build

on:
  push:
    paths:
    - '**.cs'
    - '**.csproj'
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.x.x' # The .NET SDK version to use
  REPO: "function-app/adb-to-purview/src/"
  TEST: "function-app/adb-to-purview/tests/unit-tests"

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Install dependencies
      run: dotnet restore ${{ env.REPO }}
      
    - name: Build
      run: dotnet build ${{ env.REPO }} --configuration Release --no-restore
      
    - name: Test
      run:  dotnet test ${{ env.TEST }}
      
    - name: Publish
      run: dotnet publish ${{ env.REPO }}
      
    - name: Upload WebApp1 Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: FunctionZip
        path: D:/a/Purview-ADB-Lineage-Solution-Accelerator/Purview-ADB-Lineage-Solution-Accelerator/function-app/adb-to-purview/src/bin/Debug/net6.0/publish/
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: FunctionZip
        path: ~/download
    
    - name: Display structure of downloaded files
      run: | 
        mkdir ~/artifact 
        Compress-Archive -Path ~/download/*  -DestinationPath ~/artifact/FunctionZip.zip 
        
    - name: Create Release
      uses: ncipollo/release-action@v1
      if: github.ref_type == 'tag'
      with:
        artifacts: ~/artifact/FunctionZip.zip
        token: ${{ secrets.GITHUB_TOKEN }}
