# Integration tests that call the active integration environment
# runs the pre-defined databricks notebooks

name: Integration Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # TODO: Deploy / Update Spark jobs

      - name: Start Integration Synapse SQL Pool
        run: source tests/integration/manage-sql-pool.sh start ${{ secrets.INT_SUBSCRIPTION_ID }} ${{ secrets.INT_RG_NAME }} ${{ secrets.INT_SYNAPSE_WKSP_NAME }} ${{ secrets.INT_SYNAPSE_SQLPOOL_NAME }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Install Python Requirements and Databricks CLI
        run: pip install pyapacheatlas==0.12.0 azure-identity databricks-cli
      
      - name: Configure Databricks CLI
        run: |
          echo "[DEFAULT]
          host = https://${{ secrets.INT_DATABRICKS_WKSP_ID }}.azuredatabricks.net
          token = ${{ secrets.INT_DATABRICKS_ACCESS_TOKEN }}" > ./config.ini
          export DATABRICKS_CONFIG_FILE=./config.ini


      - name: Cleanup Integration Environment
        run: python ./tests/integration/runner.py --cleanup --dontwait None None None
        env:
          PURVIEW_INTEGRATION_TARGET: ${{ secrets.INT_PURVIEW_NAME }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          DATABRICKS_CONFIG_FILE: ./config.ini

      - name: Run Integration Tests
        run: source ./tests/integration/run-test.sh ALL ${{ secrets.INT_DATABRICKS_WKSP_ID }}
        env:
          PURVIEW_INTEGRATION_TARGET: ${{ secrets.INT_PURVIEW_NAME }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          DATABRICKS_CONFIG_FILE: ./config.ini

      - name: Stop Integration Synapse SQL Pool
        run: source tests/integration/manage-sql-pool.sh stop ${{ secrets.INT_SUBSCRIPTION_ID }} ${{ secrets.INT_RG_NAME }} ${{ secrets.INT_SYNAPSE_WKSP_NAME }} ${{ secrets.INT_SYNAPSE_SQLPOOL_NAME }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
